server:
  port: 4000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
    spring.h2.console.settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:bankdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

bank:
  token-secret: jf9i4jgu83nfl0jfu57ejf7
  fee-in-percent: 3 # 0.03%
  http:
    rpc: http://localhost:8545
    connect-timeout: 30000
    read-timeout: 30000
    write-timeout: 30000
  gas:
    speed-up: 0 # 0.00%
    limit: 40000
  wallet:
    keystore-path: ./keystore
    withdraw-wallet-keystore: ./data/UTC--2022-06-26T12-18-27.288453000Z--50b67b5c76b1268887f341707c95d36640870fa2.json
    withdraw-wallet-password: password
    withdraw-wallet-address: 0x50b67b5c76b1268887f341707c95d36640870fa2
